[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@superfluid-finance/ethereum-contracts/contracts=lib/superfluid-protocol-monorepo/packages/ethereum-contracts/contracts/",
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
